### ISSUE TITLE
slotkey_input.zip link

### ISSUE THREAD

**Issue by Kurt0401** [maorninja/Guide#6]
Hi, is it possible to add a working link please for slotkey_input  ? At least it's not working for me.

Thanks in advance.

**Comment by NightScript370** [comment]
I'm not home now, but I forgot to reopen something. BRB

Sent from my iPhone

On Aug 28, 2016, at 12:07 PM, Kurt0401 <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi, is it possible to add a working link please for slotkey_input ? At least it's not working for me.

Thanks in advance.

##

**Comment by Psionic8** [comment]
it got taken down again

**Comment by NightScript370** [comment]
You do realise that this guide is vastly outdated, right???

Please look at GBATemp for the moment until I re-upload the new updated guide...

**Comment by Psionic8** [comment]
Oh okay. I am trying so many ways to get the corpse files for a game but I
can't. The rxtools won't help me out. Any suggestions? I am trying to get
Fire Emblem Awakening into CIA from 3DS format. Will FBI take 3DS format..?

**Comment by NightScript370** [comment]
Well, the current RXTools 3DS->CIA tools are broken and 99% won't be fixed due to the owner of RXTools quitting.

So you'll need to get decrypt9WIP and use the simple function.

Then, install the game with FBI.

Also, I'm not 1000% sure Fire Emblem Awakening works so once you're done, please tell me the results.

**Comment by Psionic8** [comment]
Okay well I have decrypt9WIP but it won't run. It has the logo and is set
up in homebrew launcher but when I click it it just goes through some
screens and then goes back to the main homebrew screen.

**Comment by NightScript370** [comment]
Well, thats because you are using the system with hax.

Please reboot, don't make it go to RXTools in menuhax, open the HBL in sysnand (No hacks) and open D9WIP.

**Comment by Psionic8** [comment]
HBL? Sysnand? These are all new to me. I'm using Sound Hax for homebrew.
Could you send me some instructions or something?

**Comment by NightScript370** [comment]
http://3ds.guide/

This is a guide that will help you with all your problems...

Also, just curious, why are you using RXTools? Not saying "OMG! Switch to Luma". I'm just curious...

**Comment by Psionic8** [comment]
Not exactly sure what Luna is either. I'm a noon and I just started
yesterday. I found an already made CIA of Awakened but will use that in the
future! Thanks!

**Comment by NightScript370** [comment]
Luma is another CFW, which users spam it onto other CFW. If you go to GBATemp right now and ask the same question, you'll get so much "Don't use RXTools! Use Luma!" spam that its not even funny.

The reason why everyone bashes RXTools is because it hasn't been worked on for a long time....

Just note that RXTools doesn't work on the guide mentioned above, so if you still want to use it, don't get A9LH.

**Comment by Psionic8** [comment]
Okay. I want A9LH, so do I get that and install Luna to use FBI..? How do I
install nonlegit CIAs? Idk if mine are legit.

**Comment by NightScript370** [comment]
Just follow this guide right here and it should tell you everything you need to know: https://3ds.guide/

Also, your CIA isn't legit....

**Comment by Psionic8** [comment]
I'm not sure what is and isn't legit. I got it from that ISO site or whatever
and it seems pretty legit to me. Unless I have some certain CFW then FBI
can't install nonlegit CIA files. Also thanks for the link.

On Jan 24, 2017 11:34 AM, "maorninja" <notifications@github.com> wrote:

Just follow this guide right here and it should tell you everything you
need to know: https://3ds.guide/

Also, your CIA isn't legit....

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/maorninja/Follow-up-Guide/issues/6#issuecomment-274857661>,
or mute the thread

**Comment by NightScript370** [comment]
Okay, fixed your post. It contained a link to a piracy site.

**Comment by Psionic8** [comment]
Oh okay. I got Luna set up and it's the best thing ever! Thanks a bunch.
Also, That site was wrong anyways and it was com but whatever haha

Thanks, PSIONIC

**Comment by NightScript370** [comment]
Your welcome...
